{
  "language": "node_js",
  "node_js": "lts/*",
  "cache": {
    "directories": [
      "node_modules",
      "client/node_modules"
    ]
  },
  "script": [
    "npm run build"
  ],
  "global_env": "MONGO_URL=[secure] PORT=[secure]",
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}